/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CvsForm {
        "age": number;
        "busy": boolean;
        "carBodyStyle": string;
        "counter": number;
        "email": string;
        "favoriteCar": string;
        "fullName": string;
        "hoodScoop": boolean;
        "login": boolean;
        "specialInstructions": string;
        "userName": string;
        "vegetarian": boolean;
        "volume": number;
    }
    interface CvsInput {
        "error": string;
        "hint": string;
        "label": string;
        "name": string;
        "value": string;
    }
    interface CvsInputWrapper {
        "error": string;
        "hint": string;
        "label": string;
    }
    interface CvsSecurityQuestions {
        "petName": string;
        "phoneNumber": string;
        "ssnIssued": string;
    }
}
declare global {
    interface HTMLCvsFormElement extends Components.CvsForm, HTMLStencilElement {
    }
    var HTMLCvsFormElement: {
        prototype: HTMLCvsFormElement;
        new (): HTMLCvsFormElement;
    };
    interface HTMLCvsInputElement extends Components.CvsInput, HTMLStencilElement {
    }
    var HTMLCvsInputElement: {
        prototype: HTMLCvsInputElement;
        new (): HTMLCvsInputElement;
    };
    interface HTMLCvsInputWrapperElement extends Components.CvsInputWrapper, HTMLStencilElement {
    }
    var HTMLCvsInputWrapperElement: {
        prototype: HTMLCvsInputWrapperElement;
        new (): HTMLCvsInputWrapperElement;
    };
    interface HTMLCvsSecurityQuestionsElement extends Components.CvsSecurityQuestions, HTMLStencilElement {
    }
    var HTMLCvsSecurityQuestionsElement: {
        prototype: HTMLCvsSecurityQuestionsElement;
        new (): HTMLCvsSecurityQuestionsElement;
    };
    interface HTMLElementTagNameMap {
        "cvs-form": HTMLCvsFormElement;
        "cvs-input": HTMLCvsInputElement;
        "cvs-input-wrapper": HTMLCvsInputWrapperElement;
        "cvs-security-questions": HTMLCvsSecurityQuestionsElement;
    }
}
declare namespace LocalJSX {
    interface CvsForm {
        "age"?: number;
        "busy"?: boolean;
        "carBodyStyle"?: string;
        "counter"?: number;
        "email"?: string;
        "favoriteCar"?: string;
        "fullName"?: string;
        "hoodScoop"?: boolean;
        "login"?: boolean;
        "specialInstructions"?: string;
        "userName"?: string;
        "vegetarian"?: boolean;
        "volume"?: number;
    }
    interface CvsInput {
        "error"?: string;
        "hint"?: string;
        "label"?: string;
        "name"?: string;
        "value"?: string;
    }
    interface CvsInputWrapper {
        "error"?: string;
        "hint"?: string;
        "label"?: string;
    }
    interface CvsSecurityQuestions {
        "petName"?: string;
        "phoneNumber"?: string;
        "ssnIssued"?: string;
    }
    interface IntrinsicElements {
        "cvs-form": CvsForm;
        "cvs-input": CvsInput;
        "cvs-input-wrapper": CvsInputWrapper;
        "cvs-security-questions": CvsSecurityQuestions;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cvs-form": LocalJSX.CvsForm & JSXBase.HTMLAttributes<HTMLCvsFormElement>;
            "cvs-input": LocalJSX.CvsInput & JSXBase.HTMLAttributes<HTMLCvsInputElement>;
            "cvs-input-wrapper": LocalJSX.CvsInputWrapper & JSXBase.HTMLAttributes<HTMLCvsInputWrapperElement>;
            "cvs-security-questions": LocalJSX.CvsSecurityQuestions & JSXBase.HTMLAttributes<HTMLCvsSecurityQuestionsElement>;
        }
    }
}
